### ISSUE TITLE
Feature 4: Implement Vehicle Search & Filter

### ISSUE THREAD

**Issue by zhoda-lii** [zhoda-lii/vehicle-comparator#9]

**Comment by lancemiranoo** [comment]
Added Filter Buttons

**Comment by zhoda-lii** [comment]
Added search feature. Expected behavior does not match with the actual. For reimplementation.
[Expected] Cards should be filtered depending on the input to the search bar.
[Actual] A clickable div shows below the search bar. Cards are not filtered.

**Comment by zhoda-lii** [comment]
Reimplemented.
